### ISSUE TITLE
No working with example

### ISSUE THREAD

**Issue by CRAG666** [ProtDos/pq-ntru#1]
It seems that your code has implementation problems.
Code:
```python
import pq_ntru


pq_ntru.generate_keys("key_filename", mode="moderate")

enc = pq_ntru.encrypt("key_filename", "message")

dec = pq_ntru.decrypt("key_filename", enc)

print(dec)

```

Error code:
```
Traceback (most recent call last):
  File "/home/think-crag/Documentos/maestria/Codificacion/ntru/main.py", line 8, in <module>
    dec = pq_ntru.decrypt("key_filename", enc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/think-crag/.cache/pypoetry/virtualenvs/ntru-Fnm-_lHI-py3.12/lib/python3.12/site-packages/pq_ntru/ntru.py", line 139, in decrypt
    D.readPriv(name + ".priv")
  File "/home/think-crag/.cache/pypoetry/virtualenvs/ntru-Fnm-_lHI-py3.12/lib/python3.12/site-packages/pq_ntru/NTRUdecrypt.py", line 229, in readPriv
    self.f = np.array(f.readline().split(" "), dtype=int)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#'h
```

**Comment by ProtDos** [comment]
Hey. I'll get into it

**Comment by ProtDos** [comment]
@CRAG666 

I have updated the repository. Please check it down below.
